version: "3.8"

services:
  movie-book:
    image: evahteri/movie-book-recommender:container2
    ports:
      - 5000:5000
    container_name: container2
  watchtower:
    image: containrrr/watchtower
    environment:
      -  WATCHTOWER_POLL_INTERVAL=60 # Poll every 60 seconds
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower
    