name: Health Checks

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
      - name: Install Lint
        run: pip install pylint
      - name: Run Lint
        run: pylint --fail-under 5.0 main/services
      - name: Cypress install
        working-directory: ./main
        run: npm install --legacy-peer-deps
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          working-directory: ./main/src
          install: false
          browser: chrome
          start: npm start
          command: npm run test:e2e
