name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Flask
        run: pip install flask
      - name: Install dependencies
        run: pip install -r requirements.txt   
      - name: Install Lint
        run: pip install pylint
      - name: Run Lint
        run: pylint --fail-under 5.0 src/services src/repository src/tests
      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: evahteri/movie-book-container:container2
